### PR TITLE
Updated Python + Readme

### PR DESCRIPTION
**Pull request by RosadinTV**
-Python 3.5.2 updated to @beardypig version
-Readme updated to give instructions

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me! Are all those `<br>`s because it gets compiled in and is required?

**Comment by RosadinTV** [comment]
@gravyboat I used <br> to put new lines in the "README.md" file (to improve 'visual style') 😛

**Comment by beardypig** [comment]
Doesn't markdown render two new lines as a `<br />`?

**Comment by bastimeyer** [comment]
Two new (empty) lines separate two text paragraph blocks. To force a simple line break, two spaces need to be added at the end of the line.

https://daringfireball.net/projects/markdown/syntax#p
https://help.github.com/categories/writing-on-github/

**Comment by beardypig** [comment]
Ah, well there ya go :-)

**Pull request merged**
